2018/01/28 03:01:50 [error] [exception.CHttpException.404] CHttpException: The requested view "Demo 404 page" was not found. in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('Demo 404 page')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\Test\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/test/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/test/
---
2018/01/28 03:06:05 [error] [exception.CHttpException.404] CHttpException: The requested view "Demo 404 page" was not found. in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('Demo 404 page')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\Test\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/test/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/test/index.php?r=site/page&view=buttons_and_icons
---
2018/01/28 03:13:39 [error] [exception.CHttpException.404] CHttpException: The requested view "Demo 404 page" was not found. in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('Demo 404 page')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\Test\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/test/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost/test/index.php?r=site/page&view=buttons_and_icons
---
2018/01/28 03:56:34 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "login.php". in C:\xampp\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Test\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/test/index.php?r=site/login.php
---
2018/01/28 04:08:06 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "login.php". in C:\xampp\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Test\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/test/index.php?r=site/login.php
---
2018/01/28 04:10:23 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "login.php". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login.php')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Test\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/test/index.php?r=login.php
---
2018/01/28 04:34:05 [error] [php] include(Employee.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Test\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 C:\xampp\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\Test\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Test\index.php(13): CWebApplication->run()
REQUEST_URI=/Test/index.php?r=site/login
in C:\xampp\htdocs\Test\protected\components\UserIdentity.php (13)
in C:\xampp\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/28 04:50:27 [error] [php] include(Employee.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Test\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 C:\xampp\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\Test\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Test\index.php(13): CWebApplication->run()
REQUEST_URI=/Test/index.php?r=site/login
in C:\xampp\htdocs\Test\protected\components\UserIdentity.php (13)
in C:\xampp\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/28 04:51:08 [error] [php] include(Employee.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Test\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 C:\xampp\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\Test\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Test\index.php(13): CWebApplication->run()
REQUEST_URI=/Test/index.php?r=site/login
in C:\xampp\htdocs\Test\protected\components\UserIdentity.php (13)
in C:\xampp\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/28 04:53:58 [error] [php] include(Employee.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Test\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 C:\xampp\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\Test\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Test\index.php(13): CWebApplication->run()
REQUEST_URI=/Test/index.php?r=site/login
in C:\xampp\htdocs\Test\protected\components\UserIdentity.php (13)
in C:\xampp\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/28 05:29:04 [error] [php] include(Employee.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Test\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 C:\xampp\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\Test\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Test\index.php(13): CWebApplication->run()
REQUEST_URI=/Test/index.php?r=site/login
in C:\xampp\htdocs\Test\protected\components\UserIdentity.php (13)
in C:\xampp\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/28 05:31:20 [error] [php] include(Employee.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Test\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 C:\xampp\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\Test\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Test\index.php(13): CWebApplication->run()
REQUEST_URI=/Test/index.php?r=site/login
in C:\xampp\htdocs\Test\protected\components\UserIdentity.php (13)
in C:\xampp\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/29 13:57:57 [error] [php] include(Employee.php): failed to open stream: No such file or directory (C:\xampp1\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp1\htdocs\Test\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 C:\xampp1\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#2 C:\xampp1\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp1\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp1\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp1\htdocs\Test\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp1\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp1\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp1\htdocs\Test\index.php(13): CWebApplication->run()
REQUEST_URI=/Test/
in C:\xampp1\htdocs\Test\protected\components\UserIdentity.php (13)
in C:\xampp1\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp1\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/29 14:14:56 [error] [php] include(MUser.php): failed to open stream: No such file or directory (C:\xampp1\htdocs\yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp1\htdocs\Test\protected\components\UserIdentity.php(14): spl_autoload_call()
#1 C:\xampp1\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#2 C:\xampp1\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp1\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp1\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp1\htdocs\Test\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp1\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp1\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp1\htdocs\Test\index.php(13): CWebApplication->run()
REQUEST_URI=/Test/
in C:\xampp1\htdocs\Test\protected\components\UserIdentity.php (14)
in C:\xampp1\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp1\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/29 14:18:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'k24test'' in C:\xampp1\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp1\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp1\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp1\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(672): CActiveRecord->getDbConnection()
#6 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(1463): CActiveRecord->getCommandBuilder()
#7 C:\xampp1\htdocs\Test\protected\components\UserIdentity.php(14): CActiveRecord->find('LOWER(uname)=?', Array)
#8 C:\xampp1\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#9 C:\xampp1\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp1\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp1\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#12 C:\xampp1\htdocs\Test\protected\controllers\SiteController.php(94): CModel->validate()
#13 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp1\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/Test/
HTTP_REFERER=http://localhost:8080/Test/
---
2018/01/29 14:20:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'k24test'' in C:\xampp1\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp1\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp1\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp1\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(672): CActiveRecord->getDbConnection()
#6 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(1463): CActiveRecord->getCommandBuilder()
#7 C:\xampp1\htdocs\Test\protected\components\UserIdentity.php(14): CActiveRecord->find('LOWER(uname)=?', Array)
#8 C:\xampp1\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#9 C:\xampp1\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp1\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp1\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#12 C:\xampp1\htdocs\Test\protected\controllers\SiteController.php(94): CModel->validate()
#13 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp1\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/Test/
HTTP_REFERER=http://localhost:8080/Test/
---
2018/01/29 14:21:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'k24test'' in C:\xampp1\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp1\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp1\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp1\htdocs\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(672): CActiveRecord->getDbConnection()
#6 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(1463): CActiveRecord->getCommandBuilder()
#7 C:\xampp1\htdocs\Test\protected\components\UserIdentity.php(14): CActiveRecord->find('LOWER(uname)=?', Array)
#8 C:\xampp1\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#9 C:\xampp1\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp1\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp1\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#12 C:\xampp1\htdocs\Test\protected\controllers\SiteController.php(94): CModel->validate()
#13 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp1\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#19 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/Test/
HTTP_REFERER=http://localhost:8080/Test/
---
2018/01/29 14:22:33 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uname' in 'where clause'. The SQL statement executed was: SELECT * FROM `user` `t` WHERE LOWER(uname)=? LIMIT 1.
in C:\xampp1\htdocs\Test\protected\components\UserIdentity.php (14)
in C:\xampp1\htdocs\Test\protected\models\LoginForm.php (54)
in C:\xampp1\htdocs\Test\protected\controllers\SiteController.php (94)
2018/01/29 14:22:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uname' in 'where clause'. The SQL statement executed was: SELECT * FROM `user` `t` WHERE LOWER(uname)=? LIMIT 1' in C:\xampp1\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(1359): CDbCommand->queryRow()
#2 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(1464): CActiveRecord->query(Object(CDbCriteria))
#3 C:\xampp1\htdocs\Test\protected\components\UserIdentity.php(14): CActiveRecord->find('LOWER(uname)=?', Array)
#4 C:\xampp1\htdocs\Test\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#5 C:\xampp1\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp1\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp1\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 C:\xampp1\htdocs\Test\protected\controllers\SiteController.php(94): CModel->validate()
#9 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp1\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#15 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/Test/
HTTP_REFERER=http://localhost:8080/Test/
---
2018/01/29 14:24:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in C:\xampp1\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page_after_logi...')
#1 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page_after_logi...')
#2 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Test/index.php?r=site/page_after_login
HTTP_REFERER=http://localhost:8080/Test/
---
2018/01/29 14:29:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in C:\xampp1\htdocs\yii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\web\CController.php(270): CController->missingAction('page_after_logi...')
#1 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page_after_logi...')
#2 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Test/index.php?r=site/page_after_login
HTTP_REFERER=http://localhost:8080/Test/
---
2018/01/29 14:31:07 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp1\htdocs\yii\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp1\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp1\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\xampp1\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp1\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Test/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/Test/index.php?r=user/create
---
2018/01/29 14:36:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp1\htdocs\yii\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp1\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp1\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\xampp1\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp1\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member/admin')
#9 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Test/index.php?r=member/admin
HTTP_REFERER=http://localhost:8080/Test/index.php?r=member/create
---
2018/01/29 15:39:06 [error] [exception.CException] exception 'CException' with message 'Alias "zii.widget.jui.CJuiDatePicker" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp1\htdocs\yii\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\web\CWidgetFactory.php(146): YiiBase::import('zii.widget.jui....', true)
#1 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(MemberController), 'zii.widget.jui....', Array)
#2 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(181): CBaseController->createWidget('zii.widget.jui....', Array)
#3 C:\xampp1\htdocs\Test\protected\views\member\_form.php(37): CBaseController->widget('zii.widget.jui....', Array)
#4 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#5 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#6 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#7 C:\xampp1\htdocs\Test\protected\views\member\create.php(18): CController->renderPartial('_form', Array)
#8 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#9 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#10 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#11 C:\xampp1\htdocs\yii\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#12 C:\xampp1\htdocs\Test\protected\controllers\MemberController.php(79): CController->render('create', Array)
#13 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): MemberController->actionCreate()
#14 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#16 C:\xampp1\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp1\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#18 C:\xampp1\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp1\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#23 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member/create')
#24 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#25 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/Test/index.php?r=member/create
HTTP_REFERER=http://localhost:8080/Test/index.php?r=member/index
---
2018/01/29 15:40:33 [error] [exception.CException] exception 'CException' with message 'Alias "zii.widget.jui.CJuiDatePicker" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp1\htdocs\yii\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\web\CWidgetFactory.php(146): YiiBase::import('zii.widget.jui....', true)
#1 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(MemberController), 'zii.widget.jui....', Array)
#2 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(181): CBaseController->createWidget('zii.widget.jui....', Array)
#3 C:\xampp1\htdocs\Test\protected\views\member\_form.php(40): CBaseController->widget('zii.widget.jui....', Array)
#4 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#5 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#6 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#7 C:\xampp1\htdocs\Test\protected\views\member\create.php(18): CController->renderPartial('_form', Array)
#8 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#9 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#10 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#11 C:\xampp1\htdocs\yii\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#12 C:\xampp1\htdocs\Test\protected\controllers\MemberController.php(79): CController->render('create', Array)
#13 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): MemberController->actionCreate()
#14 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#16 C:\xampp1\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp1\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#18 C:\xampp1\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp1\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#23 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member/create')
#24 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#25 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/Test/index.php?r=member/create
HTTP_REFERER=http://localhost:8080/Test/index.php?r=member/index
---
2018/01/29 15:42:03 [error] [exception.CException] exception 'CException' with message 'Alias "zii.widget.jui.CJuiDatePicker" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp1\htdocs\yii\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\web\CWidgetFactory.php(146): YiiBase::import('zii.widget.jui....', true)
#1 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(MemberController), 'zii.widget.jui....', Array)
#2 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(181): CBaseController->createWidget('zii.widget.jui....', Array)
#3 C:\xampp1\htdocs\Test\protected\views\member\_form.php(49): CBaseController->widget('zii.widget.jui....', Array)
#4 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#5 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#6 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#7 C:\xampp1\htdocs\Test\protected\views\member\create.php(18): CController->renderPartial('_form', Array)
#8 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#9 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#10 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#11 C:\xampp1\htdocs\yii\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#12 C:\xampp1\htdocs\Test\protected\controllers\MemberController.php(79): CController->render('create', Array)
#13 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): MemberController->actionCreate()
#14 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#16 C:\xampp1\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp1\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#18 C:\xampp1\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp1\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#23 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member/create')
#24 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#25 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/Test/index.php?r=member/create
HTTP_REFERER=http://localhost:8080/Test/index.php?r=member/index
---
2018/01/29 15:42:57 [error] [exception.CException] exception 'CException' with message 'Property "CJuiDatePicker.htmlOption" is not defined.' in C:\xampp1\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\web\CWidgetFactory.php(161): CComponent->__set('htmlOption', Array)
#1 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(MemberController), 'zii.widgets.jui...', Array)
#2 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(181): CBaseController->createWidget('zii.widgets.jui...', Array)
#3 C:\xampp1\htdocs\Test\protected\views\member\_form.php(49): CBaseController->widget('zii.widgets.jui...', Array)
#4 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#5 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#6 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#7 C:\xampp1\htdocs\Test\protected\views\member\create.php(18): CController->renderPartial('_form', Array)
#8 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#9 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#10 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#11 C:\xampp1\htdocs\yii\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#12 C:\xampp1\htdocs\Test\protected\controllers\MemberController.php(79): CController->render('create', Array)
#13 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): MemberController->actionCreate()
#14 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#16 C:\xampp1\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp1\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#18 C:\xampp1\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp1\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#23 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member/create')
#24 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#25 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/Test/index.php?r=member/create
HTTP_REFERER=http://localhost:8080/Test/index.php?r=member/index
---
2018/01/29 15:43:15 [error] [exception.CException] exception 'CException' with message 'Property "Member.birthdate" is not defined.' in C:\xampp1\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp1\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('birthdate')
#1 C:\xampp1\htdocs\yii\framework\web\helpers\CHtml.php(2747): CActiveRecord->__get('birthdate')
#2 C:\xampp1\htdocs\yii\framework\web\helpers\CHtml.php(2470): CHtml::resolveValue(Object(Member), 'birthdate')
#3 C:\xampp1\htdocs\yii\framework\web\helpers\CHtml.php(1540): CHtml::activeInputField('text', Object(Member), 'birthdate', Array)
#4 C:\xampp1\htdocs\yii\framework\zii\widgets\jui\CJuiDatePicker.php(84): CHtml::activeTextField(Object(Member), 'birthdate', Array)
#5 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(182): CJuiDatePicker->run()
#6 C:\xampp1\htdocs\Test\protected\views\member\_form.php(49): CBaseController->widget('zii.widgets.jui...', Array)
#7 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#8 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#9 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#10 C:\xampp1\htdocs\Test\protected\views\member\create.php(18): CController->renderPartial('_form', Array)
#11 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp1\\htdoc...')
#12 C:\xampp1\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp1\\htdoc...', Array, true)
#13 C:\xampp1\htdocs\yii\framework\web\CController.php(872): CBaseController->renderFile('C:\\xampp1\\htdoc...', Array, true)
#14 C:\xampp1\htdocs\yii\framework\web\CController.php(785): CController->renderPartial('create', Array, true)
#15 C:\xampp1\htdocs\Test\protected\controllers\MemberController.php(79): CController->render('create', Array)
#16 C:\xampp1\htdocs\yii\framework\web\actions\CInlineAction.php(49): MemberController->actionCreate()
#17 C:\xampp1\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#19 C:\xampp1\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp1\htdocs\yii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#21 C:\xampp1\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp1\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp1\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp1\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#26 C:\xampp1\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member/create')
#27 C:\xampp1\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#28 C:\xampp1\htdocs\Test\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/Test/index.php?r=member/create
HTTP_REFERER=http://localhost:8080/Test/index.php?r=member/index
---
